### ISSUE TITLE
Gen 2 helper URL broken

### ISSUE THREAD

**Issue by wartab** [entrpntr/gsc-helper#1]
Hey,

I do not know if this is on purpose, but the link to the Gen 2 helper is broken and I cannot download it anymore. I'm assuming there are not many people who know how to use Gradle and are ready to do that besides me and the PSR members who are coincidentally devs :)

Kind regards :)

**Comment by entrpntr** [comment]
Dropbox public folder functionality was shut off a couple months ago, and I hadn't received any prior notice, which is why the links vanished. I was planning on implementing a few small things and switching over to github releases, but ended up procrastinating on making any changes. I just pushed out an initial release on github with changes from the last 11 months and updated the links on the PSR forums and speedrun.com.
